name: Build Android APK

on:
  push:
    branches:
      - principal
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Criar Projeto e Compilar
        run: |
          cordova create app com.minhatv.online "TV Online"
          cp index.html app/www/index.html
          cd app
          cordova platform add android
          cordova build android --debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-tv
          path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
